services:

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  worker:
    build: .
    command: node worker.entry.js
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  dashboard:
    build: ./dashboard
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  redis_data:
